'use client'

import { ProviderProduct } from "@/context/useProductContext";
import "./globals.css";
import { Inter } from "next/font/google";
import { QueryClientProvider, QueryClient } from "react-query";

const inter = Inter({ subsets: ["latin"] });
const queryClient = new QueryClient();

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <QueryClientProvider client={queryClient}>
      <ProviderProduct>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </ProviderProduct>
    </QueryClientProvider>
  );
}
