'use client'

import "./globals.css";
import { Saira } from "@next/font/google";
import { QueryClientProvider, QueryClient } from "react-query";
import { ProviderProductCarrinho } from "@/context/useProductsCarrinho";
import 'react-toastify/dist/ReactToastify.css';

const saira = Saira({
  weight: "400",
  display: "swap",
  subsets:['latin']
});

const queryClient = new QueryClient();

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <QueryClientProvider client={queryClient}>
        <ProviderProductCarrinho>
          <html lang="en">
            <body className={saira.className}>{children}</body>
          </html>
        </ProviderProductCarrinho>
    </QueryClientProvider>
  );
}
